image:
    file: .gitpod.Dockerfile

tasks:
    - name: Start redis
      command: redis-server
    - name: Build server
      before: go mod download
      init: |
          cd frontend
          npm install
          npm run build
          cd ..
      command: go run cmd/main.go

ports:
    - port: 3333
      onOpen: notify
      name: Server
      description: Backend of Cards Against DHBW
      visibility: public
    - port: 6379
      onOpen: notify
      name: redis
      description: redis server for Cards Against DHBW
      visibility: private
