image: gitpod/workspace-full

tasks:
    - name: Build server
      before: go mod download
      command: go run cmd/main.go

ports:
    - port: 3333
      onOpen: notify
      name: Server
      description: Backend of Cards Against DHBW
      visibility: public
