openapi: 3.0.0

info:
    title: Cards Against DHBW API
    description: A cards game.
    version: 1.0.0

servers:
    - url: http://localhost:5000/v1
      description: Local server

paths:
    /new:
        get:
            summary: Create a new game
            description: Create a new game
            operationId: new

            responses:
                "200":
                    description: Metadata for a new game
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Game"

    /join/{code}:
        get:
            summary: Join a game
            description: Join a game
            operationId: join

            parameters:
                - name: code
                  in: path
                  description: Game code
                  required: true
                  schema:
                      type: string

            responses:
                "200":
                    description: Metadata for the game containing the player's name
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Game"

components:
    schemas:
        Game:
            type: object
            description: Data for a new game.

            properties:
                id:
                    type: string
                    description: Game identifier used to join the game.
                    example: d84nt8

                playerName:
                    type: string
                    description: Player name.
                    example: UGV0ZXI=
